version: "2"
output:
  formats:
    text:
      path: stdout
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - embeddedstructfieldcheck
    - errchkjson
    - exhaustruct
    - forbidigo
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - godoclint
    - godox
    - gosmopolitan
    - iotamixing
    - ireturn
    - maintidx
    - mnd
    - modernize
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - promlinter
    - tagliatelle
    - testifylint
    - testpackage
    - wrapcheck
    - wsl
    - wsl_v5
  settings:
    ireturn:
      allow:
        - error
        - generic
        - stdlib
        - empty
    misspell:
      mode: restricted
      locale: US
    revive:
      rules:
        - name: var-naming
          arguments:
            - - ID
              - API
          disabled: false
    staticcheck:
      checks:
        - all
        - -ST1003
    varnamelen:
      max-distance: 15
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        text: don't use ALL_CAPS in Go names
      - linters:
          - revive
        text: 'var-naming: avoid package names that conflict with Go standard library package names'
        path: errors/
      - linters:
          - revive
        text: 'var-naming: avoid meaningless package names'
        path: utils/
      - linters:
          - staticcheck
        text: 'cloud.google.com/go/pubsub.*is deprecated: Please use cloud.google.com/go/pubsub/v2'
    paths:
      - openapi
      - scripts
      - tmp
      - playground
      - testrun
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - openapi
      - scripts
      - tmp
      - playground
      - testrun
      - third_party$
      - builtin$
      - examples$
