// Package emoji provides emoji constants for terminal output and UI.
package emoji

const (
	Spool        = "🧵"
	Yarn         = "🧶"
	LabCoat      = "🥼"
	Goggles      = "🥽"
	Document     = "📝"
	Directory    = "📁"
	Link         = "🔗"
	Turtle       = "🐢"
	Rabbit       = "🐇"
	Fire         = "🔥"
	ThumbsUp     = "👍"
	ThumbsDown   = "👎"
	Magnifying   = "🔍"
	MagnifyingUp = "🔎"
	Briefcase    = "💼"
	Comet        = "☄️"
	Planet       = "🪐"
	Loudspeaker  = "📢"
	Warning      = "⚠️"
	NoEntry      = "⛔"
	Prohibited   = "🚫"
	Stop         = "🛑"
	Ok           = "✓"
	NotOk        = "✗"
	Construction = "🚧"
	Robot        = "🤖"
	Desktop      = "🖥️"
	Laptop       = "💻"
	Keyboard     = "⌨️"
	Checkmark    = "☑️"
	Stopwatch    = "⏱️"
	Clock        = "🕰️"
	Eyes         = "👀"
	Eye          = "👁️"
	Moon         = "🌙"
	Sun          = "☀️"
	Star         = "⭐"
	Box          = "📦"
	Rocket       = "🚀"
)
